services:
    db:
        image: mysql:latest
        volumes:
        - "./.mysql-data/db:/var/lib/mysql"
        restart: always
        ports:
        - 3306:3306
        environment:
            MYSQL_DATABASE: practica8-softwareavanzado
            MYSQL_USER: root
            MYSQL_PASSWORD: 12345
            MYSQL_ROOT_PASSWORD: 12345
        network_mode: "host"
        ports:
            - "3306:3306"
    app:
        build:
            context: ./app/
            dockerfile: Dockerfile
        container_name: app-nodejs
        ports:
            - "80:80"