services: 
    db:
        build:
            context: ./db
            dockerfile: Dockerfile
        container_name: database-mysql
        restart: always
        environment:
            MYSQL_DATABASE: practica8-softwareavanzado
            MYSQL_USER: root
            MYSQL_PASSWORD: 12345
            MYSQL_ROOT_PASSWORD: 12345
        network_mode: "host"
        ports:
            - "3306:3306"
        volumes: 
            - "./data:/var/lib/mysql"
    app:
        build:
            context: ./app/
            dockerfile: Dockerfile
        container_name: app-nodejs
        ports:
            - "80:80"