services: 
    db:
        build:
            context: ./db
            dockerfile: Dockerfile
        container_name: database-mysql
        environment:
            MYSQL_DATABASE: practica8-softwareavanzado
            MYSQL_USER: root
            MYSQL_PASSWORD: 12345
            MYSQL_ROOT_PASSWORD: 12345
        entrypoint: entrypoint.sh
        ports:
            - "3306:3306"
    app:
        build:
            context: ./app/
            dockerfile: Dockerfile
        container_name: app-nodejs
        ports:
            - "80:80"